GET http://localhost:9000/login

###

POST http://localhost:9000/login/admin
Content-Type: application/json

{
  "name": "benek",
  "password":"benek"
}

###

GET http://localhost:9000/messages

###

POST http://localhost:9000/messages
Content-Type: application/json

{
"areaValue":"zerowy",

}

####
DELETE http://localhost:9000/messages/delete
Content-Type: application/json

{
  "id":1
}